apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.service.port }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://{{ .Values.mysql.name }}:3306/{{ .Values.mysql.db.name }}?useUnicode=true&characterEncoding=UTF-8" 
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.mysql.db.user }}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.name }}-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: app-uploads-storage
          mountPath: {{ .Values.app.persistence.mountPath }}
      volumes:
      - name: app-uploads-storage
        persistentVolumeClaim:
          claimName: {{ .Values.app.name }}-pvc