apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.name }}
spec:
  serviceName: {{ .Values.mysql.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
      - name: {{ .Values.mysql.name }}
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.name }}-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.db.name }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.db.user }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.name }}-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: {{ .Values.mysql.persistence.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ {{ .Values.mysql.persistence.accessMode }} ]
      storageClassName: {{ .Values.mysql.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.mysql.persistence.size }}